spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?serverTimezone=UTC
    username: omar
    password: omar
    driver-class-name: com.mysql.cj.jdbc.Driver
# specify DBMS
  jpa:
    database: MYSQL
# Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081